name: sarv_invoice_module_plugin
description: savr invoice module for POS and Applicatioin.
version: 0.0.1
auther: Mehran shoghi<mehranshoqi@outlook.com>
homepage: https://github.com/mehranshoqi/sarv_invoice_module_plugin.git

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sizer:
  fluro: ^2.0.3
  iconsax: ^0.0.8
  modal_bottom_sheet:
  # desktop_window: ^0.4.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  dio: ^4.0.6
  injectable: ^1.5.3
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  horizontal_data_table: ^4.1.1+1
  # image_picker:
  # editable: ^2.0.0
  cupertino_icons: ^1.0.2
  oktoast: ^3.2.0
  pretty_dio_logger: ^1.1.1
  flutter_secure_storage: ^5.0.2
  # file_picker: ^5.0.0
  expandable: ^5.0.1
  loading_animation_widget: ^1.2.0+2
  # dropdown_search: ^5.0.2
  shamsi_date: ^1.0.1
  android_pos:
    git:
      url: https://github.com/mehranshoqi/pos-p1000.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.5
  freezed: ^1.1.1
  build_runner: ^2.1.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
